Repository ElementsProject/elements, pull requests merged in 2019-09, with the labels that each got.

#704 RPC: Fix tweakfedpegscript for dynafed, add basic test
  src/rpc/misc.cpp
  test/functional/rpc_tweakfedpeg.py
Labels: bug, needs port

#705 [0.18 backport] RPC: Fix tweakfedpegscript for dynafed, add basic test
  src/rpc/misc.cpp
  test/functional/rpc_tweakfedpeg.py
Labels: 0.18

#717 Add legacy pak arg for custom chains
  src/chainparams.cpp
  src/chainparamsbase.cpp
Labels: needs port

#725 [0.18 backport] [HF] Dynafed blocks must have sighash byte #723
  src/block_proof.cpp
  src/hash.h
  src/rpc/mining.cpp
  src/script/generic.hpp
  src/wallet/rpcwallet.cpp
Labels: 0.18
