Repository ElementsProject/elements, pull requests merged in 2019-03, with the labels that each got.

#480 remove redundant value validity check
  src/validation.cpp
Labels: 0.14.1

#472 Add comment on witness-null issuance transactions' invalidity
  src/validation.cpp
Labels: 0.14.1

#512 Add secure reporting document, link in README
  README.md
  SECURITY.md
Labels: 0.14.1

#519 [0.17] backport "Remove comma for `claimpegin` in command line help info "
  src/wallet/rpcwallet.cpp
Labels: 0.17

#517 [0.17] backport "Validation: stop logging fake pow data"
  src/validation.cpp
Labels: 0.17

#518 [0.17] Manual pak RPC calls
  src/wallet/rpcwallet.cpp
Labels: 0.17

#516 [0.17] Fix progress reporting issue
  src/interfaces/node.cpp
  src/rpc/blockchain.cpp
  src/validation.cpp
  src/validation.h
  src/wallet/wallet.cpp
  test/functional/feature_progress.py
  test/functional/test_runner.py
Labels: 0.17

#508 Let's try to have more builds complete within allotted time
  .travis.yml
Labels: 0.17

#522 Fix occasional mempool_packages failure
  test/functional/mempool_packages.py
Labels: 0.17

#523 [0.17] Fix no wallet build
  .travis.yml
Labels: 0.17

#525 [0.17] Disallow extended encoding for non-witness transactions
  src/primitives/transaction.h
Labels: 0.17

#524 [0.17] Make validatepegin default to true if has parent chain
  src/init.cpp
  src/pegins.cpp
  src/script/script.h
  src/test/test_bitcoin.cpp
  src/validation.cpp
  src/wallet/rpcwallet.cpp
  test/bitcoin_functional/functional/test_framework/util.py
  test/functional/test_framework/util.py
Labels: 0.17

#526 [0.17] Add test for superfulous witness record in deserialization
  test/functional/p2p_segwit.py
Labels: 0.17

#533 Add Travis fedpeg test with downloaded bitcoind
  .travis.yml
  .travis/test_06_script.sh
  src/chainparams.cpp
  test/functional/feature_fedpeg.py
  test/functional/test_framework/test_framework.py
  test/functional/test_framework/test_node.py
Labels: 0.17

#402 Disallow extended encoding for non-witness transactions
  src/primitives/transaction.h
Labels: 0.14.1

#513 Actually test multisig rawreissuance
  qa/rpc-tests/feature_issuance.py
Labels: 0.14.1, bug

#514 fix vector length calculation for targets in BlindTransaction
  src/blind.cpp
Labels: 0.14.1, needs port
