Repository ElementsProject/elements, pull requests merged in 2019-06, with the labels that each got.

#625 Disallow issuance calls in bitcoin mode
  src/wallet/rpcwallet.cpp
Labels: needs port

#629 Fixup some QT-only credit computing code
  src/interfaces/wallet.cpp
  src/interfaces/wallet.h
  src/qt/transactiondesc.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: bug, needs port

#647 Move MainchainRPCCheck to its own schedule to avoid waiting for itself
  src/init.cpp
Labels: bug

#652 [0.17 backport] Properly rename liquid windows binaries
  contrib/gitian-descriptors/gitian-liquid-win.yml
Labels: 0.17

#662 [0.17 backport] FundTransaction: mark all change keys as kept #660
  src/wallet/wallet.cpp
Labels: 0.17

#660 FundTransaction: mark all change keys as kept
  src/wallet/wallet.cpp
Labels: needs port
